name: Greetings
  
on: [pull_request, issues]

jobs:
  print-token:
    permissions: write-all
    name: print-token
    environment: dev
    # needs: pre-pkr
    runs-on: ubuntu-latest
  
    greeting:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for reporting issues'
          pr-message: 'Thanks for sending your prs'
