name: Greetings
  
on: [pull_request, issues]

jobs:
  permissions:
    id-token: write
    contents: read
    issues: write
    pull-requests: write
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for reporting issues'
        pr-message: 'Thanks for sending your prs'
