name: Greetings

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        issue-message: 'Thanks for reporting issues'
        pr-message: 'Thanks for sending your prs'
